force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Quantity_in_Stock__c.field-meta.xml
<CustomField>
    <fullName>Quantity_in_Stock__c</fullName>
    <label>Quantity in Stock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RestockProduct__c/RestockProduct__c.object-meta.xml
<CustomObject>
    <label>RestockProduct</label>
    <nameField>
        <label>RestockProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RestockProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RestockProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>RestockProducts</relationshipLabel>
    <relationshipName>RestockProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RestockProduct__c/fields/Quantity_Restocked__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Restocked__c</fullName>
    <label>Quantity Restocked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateProductRestockBatch.cls
public class CreateProductRestockBatch implements Database.Batchable<SObject> {

    
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT Id, Name, Quantity_in_Stock__c FROM Product__c WHERE Quantity_in_Stock__c < 50');
    }
    public void execute(Database.BatchableContext context, List<Product__c> products) {
        
        List<RestockProduct__c> restockToInsert = new List<RestockProduct__c>();
        for (Product__c pro : products) {
            RestockProduct__c newRestock = new RestockProduct__c(
                Quantity_Restocked__c = 200,
                Product__c = pro.Id,
                Name = pro.Name
                
            );
            restockToInsert.add(newRestock);
        }
        if(restockToInsert.size() < 0){
        insert restockToInsert;
        }
    }

    
    public void finish(Database.BatchableContext context) {
        System.debug('Done');
    }
}